In [1]:
import pandas as pd, numpy as np
np.set_printoptions(suppress=True)# 关掉科学计数法
import glob
import os
import csv
# 一次性merge多个pct_chg
from functools import reduce
from datetime import datetime, timedelta
import statsmodels.api as sm
from statsmodels import regression

# import yfinance as yf
import tushare as ts
import time, urllib
ts.set_token('8ef5ec61cdd848715c57c11d58dd71da1271f76b2420d2bac8aef123')
pro = ts.pro_api('8ef5ec61cdd848715c57c11d58dd71da1271f76b2420d2bac8aef123')

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set(context='notebook', style='darkgrid', palette='deep', font='sans-serif', font_scale=1, color_codes=False, rc=None)

from plotly.graph_objs import Scatter,Layout
import plotly
import plotly.offline as py
import numpy as np
import plotly.graph_objs as go

#setting offilne
plotly.offline.init_notebook_mode(connected=True)

In [2]:
data = pro.query('stock_basic', exchange='', list_status='L', fields='ts_code,symbol,industry')

In [6]:
data['industry'].unique()

array(['银行', '全国地产', '生物制药', '环境保护', '区域地产', '酒店餐饮', '运输设备', '综合类',
       '建筑工程', '玻璃', '家用电器', '文教休闲', '其他商业', '元器件', 'IT设备', '其他建材',
       '汽车服务', '火力发电', '医药商业', '汽车配件', '广告包装', '轻工机械', '新型电力', '多元金融',
       '饲料', '电气设备', '房产服务', '石油加工', '铅锌', '农业综合', '批发业', '通信设备', '旅游景点',
       '港口', '机场', '石油贸易', '空运', '医疗保健', '商贸代理', '化学制药', '影视音像', '工程机械',
       '软件服务', '证券', '化纤', '水泥', '专用机械', '供气供热', '农药化肥', '机床制造', '百货',
       '中成药', '路桥', '造纸', '食品', '黄金', '化工原料', '矿物制品', '水运', '日用化工',
       '机械基件', '汽车整车', '煤炭开采', '铁路', '染料涂料', '白酒', '林业', '水务', '水力发电',
       '互联网', '旅游服务', '纺织', '铝', '保险', '园区开发', '小金属', '铜', '普钢', '航空',
       '特种钢', '种植业', '出版业', '焦炭加工', '啤酒', '公路', '超市连锁', '钢加工', '渔业',
       '农用机械', '软饮料', '化工机械', '塑料', '红黄酒', '橡胶', '家居用品', '摩托车', '电器仪表',
       '服饰', '仓储物流', '纺织机械', '电器连锁', '装修装饰', '半导体', '电信运营', '石油开采', '乳制品',
       '商品城', '公共交通', '船舶', '陶瓷'], dtype=object)

In [9]:
data.head(20)

      ts_code  symbol industry
0   000001.SZ  000001       银行
1   000002.SZ  000002     全国地产
2   000004.SZ  000004     生物制药
3   000005.SZ  000005     环境保护
4   000006.SZ  000006     区域地产
5   000007.SZ  000007     酒店餐饮
6   000008.SZ  000008     运输设备
7   000009.SZ  000009      综合类
8   000010.SZ  000010     建筑工程
9   000011.SZ  000011     区域地产
10  000012.SZ  000012       玻璃
11  000014.SZ  000014     全国地产
12  000016.SZ  000016     家用电器
13  000017.SZ  000017     文教休闲
14  000019.SZ  000019     其他商业
15  000020.SZ  000020      元器件
16  000021.SZ  000021     IT设备
17  000023.SZ  000023     其他建材
18  000025.SZ  000025     汽车服务
19  000026.SZ  000026     其他商业

In [8]:
# 接下来需要找出每个industry中，mkt cap最大的