#Tickers of current S&P500 companies

In [40]:
from yahoo_fin.stock_info import *

tickers = tickers_sp500()
tickers

['A',
 'AAL',
 'AAP',
 'AAPL',
 'ABBV',
 'ABC',
 'ABMD',
 'ABT',
 'ACN',
 'ADBE',
 'ADI',
 'ADM',
 'ADP',
 'ADS',
 'ADSK',
 'AEE',
 'AEP',
 'AES',
 'AFL',
 'AIG',
 'AIV',
 'AIZ',
 'AJG',
 'AKAM',
 'ALB',
 'ALGN',
 'ALK',
 'ALL',
 'ALLE',
 'ALXN',
 'AMAT',
 'AMCR',
 'AMD',
 'AME',
 'AMGN',
 'AMP',
 'AMT',
 'AMZN',
 'ANET',
 'ANSS',
 'ANTM',
 'AON',
 'AOS',
 'APA',
 'APD',
 'APH',
 'APTV',
 'ARE',
 'ATO',
 'ATVI',
 'AVB',
 'AVGO',
 'AVY',
 'AWK',
 'AXP',
 'AZO',
 'BA',
 'BAC',
 'BAX',
 'BBY',
 'BDX',
 'BEN',
 'BF.B',
 'BIIB',
 'BK',
 'BKNG',
 'BKR',
 'BLK',
 'BLL',
 'BMY',
 'BR',
 'BRK.B',
 'BSX',
 'BWA',
 'BXP',
 'C',
 'CAG',
 'CAH',
 'CARR',
 'CAT',
 'CB',
 'CBOE',
 'CBRE',
 'CCI',
 'CCL',
 'CDNS',
 'CDW',
 'CE',
 'CERN',
 'CF',
 'CFG',
 'CHD',
 'CHRW',
 'CHTR',
 'CI',
 'CINF',
 'CL',
 'CLX',
 'CMA',
 'CMCSA',
 'CME',
 'CMG',
 'CMI',
 'CMS',
 'CNC',
 'CNP',
 'COF',
 'COG',
 'COO',
 'COP',
 'COST',
 'COTY',
 'CPB',
 'CPRT',
 'CRM',
 'CSCO',
 'CSX',
 'CTAS',
 'CTL',
 'CTSH',
 'CTVA',
 'CTXS',
 'CVS',
 'CVX',
 'CXO',
 'D',
 'DAL',
 'DD',
 'DE',
 'DFS',
 'DG',
 'DGX',
 'DHI',
 'DHR',
 'DIS',
 'DISCA',
 'DISCK',
 'DISH',
 'DLR',
 'DLTR',
 'DOV',
 'DOW',
 'DPZ',
 'DRE',
 'DRI',
 'DTE',
 'DUK',
 'DVA',
 'DVN',
 'DXC',
 'DXCM',
 'EA',
 'EBAY',
 'ECL',
 'ED',
 'EFX',
 'EIX',
 'EL',
 'EMN',
 'EMR',
 'EOG',
 'EQIX',
 'EQR',
 'ES',
 'ESS',
 'ETFC',
 'ETN',
 'ETR',
 'EVRG',
 'EW',
 'EXC',
 'EXPD',
 'EXPE',
 'EXR',
 'F',
 'FANG',
 'FAST',
 'FB',
 'FBHS',
 'FCX',
 'FDX',
 'FE',
 'FFIV',
 'FIS',
 'FISV',
 'FITB',
 'FLIR',
 'FLS',
 'FLT',
 'FMC',
 'FOX',
 'FOXA',
 'FRC',
 'FRT',
 'FTI',
 'FTNT',
 'FTV',
 'GD',
 'GE',
 'GILD',
 'GIS',
 'GL',
 'GLW',
 'GM',
 'GOOG',
 'GOOGL',
 'GPC',
 'GPN',
 'GPS',
 'GRMN',
 'GS',
 'GWW',
 'HAL',
 'HAS',
 'HBAN',
 'HBI',
 'HCA',
 'HD',
 'HES',
 'HFC',
 'HIG',
 'HII',
 'HLT',
 'HOG',
 'HOLX',
 'HON',
 'HPE',
 'HPQ',
 'HRB',
 'HRL',
 'HSIC',
 'HST',
 'HSY',
 'HUM',
 'HWM',
 'IBM',
 'ICE',
 'IDXX',
 'IEX',
 'IFF',
 'ILMN',
 'INCY',
 'INFO',
 'INTC',
 'INTU',
 'IP',
 'IPG',
 'IPGP',
 'IQV',
 'IR',
 'IRM',
 'ISRG',
 'IT',
 'ITW',
 'IVZ',
 'J',
 'JBHT',
 'JCI',
 'JKHY',
 'JNJ',
 'JNPR',
 'JPM',
 'JWN',
 'K',
 'KEY',
 'KEYS',
 'KHC',
 'KIM',
 'KLAC',
 'KMB',
 'KMI',
 'KMX',
 'KO',
 'KR',
 'KSS',
 'KSU',
 'L',
 'LB',
 'LDOS',
 'LEG',
 'LEN',
 'LH',
 'LHX',
 'LIN',
 'LKQ',
 'LLY',
 'LMT',
 'LNC',
 'LNT',
 'LOW',
 'LRCX',
 'LUV',
 'LVS',
 'LW',
 'LYB',
 'LYV',
 'MA',
 'MAA',
 'MAR',
 'MAS',
 'MCD',
 'MCHP',
 'MCK',
 'MCO',
 'MDLZ',
 'MDT',
 'MET',
 'MGM',
 'MHK',
 'MKC',
 'MKTX',
 'MLM',
 'MMC',
 'MMM',
 'MNST',
 'MO',
 'MOS',
 'MPC',
 'MRK',
 'MRO',
 'MS',
 'MSCI',
 'MSFT',
 'MSI',
 'MTB',
 'MTD',
 'MU',
 'MXIM',
 'MYL',
 'NBL',
 'NCLH',
 'NDAQ',
 'NEE',
 'NEM',
 'NFLX',
 'NI',
 'NKE',
 'NLOK',
 'NLSN',
 'NOC',
 'NOV',
 'NOW',
 'NRG',
 'NSC',
 'NTAP',
 'NTRS',
 'NUE',
 'NVDA',
 'NVR',
 'NWL',
 'NWS',
 'NWSA',
 'O',
 'ODFL',
 'OKE',
 'OMC',
 'ORCL',
 'ORLY',
 'OTIS',
 'OXY',
 'PAYC',
 'PAYX',
 'PBCT',
 'PCAR',
 'PEAK',
 'PEG',
 'PEP',
 'PFE',
 'PFG',
 'PG',
 'PGR',
 'PH',
 'PHM',
 'PKG',
 'PKI',
 'PLD',
 'PM',
 'PNC',
 'PNR',
 'PNW',
 'PPG',
 'PPL',
 'PRGO',
 'PRU',
 'PSA',
 'PSX',
 'PVH',
 'PWR',
 'PXD',
 'PYPL',
 'QCOM',
 'QRVO',
 'RCL',
 'RE',
 'REG',
 'REGN',
 'RF',
 'RHI',
 'RJF',
 'RL',
 'RMD',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RSG',
 'RTX',
 'SBAC',
 'SBUX',
 'SCHW',
 'SEE',
 'SHW',
 'SIVB',
 'SJM',
 'SLB',
 'SLG',
 'SNA',
 'SNPS',
 'SO',
 'SPG',
 'SPGI',
 'SRE',
 'STE',
 'STT',
 'STX',
 'STZ',
 'SWK',
 'SWKS',
 'SYF',
 'SYK',
 'SYY',
 'T',
 'TAP',
 'TDG',
 'TEL',
 'TFC',
 'TFX',
 'TGT',
 'TIF',
 'TJX',
 'TMO',
 'TMUS',
 'TPR',
 'TROW',
 'TRV',
 'TSCO',
 'TSN',
 'TT',
 'TTWO',
 'TWTR',
 'TXN',
 'TXT',
 'UA',
 'UAA',
 'UAL',
 'UDR',
 'UHS',
 'ULTA',
 'UNH',
 'UNM',
 'UNP',
 'UPS',
 'URI',
 'USB',
 'V',
 'VAR',
 'VFC',
 'VIAC',
 'VLO',
 'VMC',
 'VNO',
 'VRSK',
 'VRSN',
 'VRTX',
 'VTR',
 'VZ',
 'WAB',
 'WAT',
 'WBA',
 'WDC',
 'WEC',
 'WELL',
 'WFC',
 'WHR',
 'WLTW',
 'WM',
 'WMB',
 'WMT',
 'WRB',
 'WRK',
 'WST',
 'WU',
 'WY',
 'WYNN',
 'XEL',
 'XLNX',
 'XOM',
 'XRAY',
 'XRX',
 'XYL',
 'YUM',
 'ZBH',
 'ZBRA',
 'ZION',
 'ZTS']

#Top 5 Companies of Each Sector by Market Capitalization

In [4]:
import bs4 as bs
import requests
import pandas as pd
 
def sector_sp500_tickers(selectedsector):
    resp = requests.get('http://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
    soup = bs.BeautifulSoup(resp.text, 'lxml')
    table = soup.find('table', {'class': 'wikitable sortable'})

    tickers = []
    sectors = []

    for row in table.findAll('tr')[1:]:
            ticker = row.findAll('td')[0].text
            sector = row.findAll('td')[3].text

            tickers.append(ticker)
            sectors.append(sector)

    tickers = list(map(lambda s: s.strip(), tickers))
    sectors = list(map(lambda s: s.strip(), sectors))

    tickerdf = pd.DataFrame(tickers,columns=['ticker'])
    sectordf = pd.DataFrame(sectors,columns=['sector'])

    tickerandsector = pd.concat([tickerdf, sectordf], axis=1)
    filtersector = tickerandsector.loc[tickerandsector['sector'] == selectedsector]

    listoftickers =  filtersector['ticker'].tolist()
    return listoftickers

In [5]:
Industrials = sector_sp500_tickers('Industrials')
Information_Technology = sector_sp500_tickers('Information Technology')
Health_Care = sector_sp500_tickers('Health Care')
Communication_Services = sector_sp500_tickers('Communication Services')
Consumer_Discretionary = sector_sp500_tickers('Consumer Discretionary')
Consumer_Staples = sector_sp500_tickers('Consumer Staples')
Utilities = sector_sp500_tickers('Utilities')
Financials = sector_sp500_tickers('Financials')
Materials = sector_sp500_tickers('Materials')
Real_Estate = sector_sp500_tickers('Real Estate')
Energy = sector_sp500_tickers('Energy')

In [30]:
from pandas_datareader import data as pdr

def cap_sp500_tickers(selectedtickers,name_of_sector):
    cap = pdr.get_quote_yahoo(selectedtickers)['marketCap']    
    list_cap = list(cap)
    list_cap, selectedtickers = zip(*sorted(zip(list_cap, selectedtickers),reverse = True))
    
    top5 = []
    print('The Top 5 Companies from', name_of_sector, 'sector：')        
    for i in range(0,5):
        print(i+1, selectedtickers[i], list_cap[i])
        top5.append(selectedtickers[i])
    return top5

In [9]:
Industrials_top5 = cap_sp500_tickers(Industrials,'Industrials')
Industrials_top5

The Top 5 Companies from Industrials sector：
1 UNP 116021551104
2 BA 111962071040
3 LMT 107532804096
4 HON 104343740416
5 RTX 102758154240

['UNP', 'BA', 'LMT', 'HON', 'RTX']

In [10]:
Information_Technology_top5 = cap_sp500_tickers(Information_Technology,'Information Technology')
Information_Technology_top5

The Top 5 Companies from Information Technology sector：
1 AAPL 1518352990208
2 MSFT 1469443211264
3 V 430180204544
4 MA 306483986432
5 INTC 255416041472

['AAPL', 'MSFT', 'V', 'MA', 'INTC']

In [11]:
Health_Care_top5 = cap_sp500_tickers(Health_Care,'Health Care')
Health_Care_top5

The Top 5 Companies from Health Care sector：
1 JNJ 380793061376
2 UNH 278131408896
3 MRK 192689799168
4 PFE 183822090240
5 ABBV 167079591936

['JNJ', 'UNH', 'MRK', 'PFE', 'ABBV']

In [12]:
Communication_Services_top5 = cap_sp500_tickers(Communication_Services,'Communication Services')
Communication_Services_top5

The Top 5 Companies from Communication Services sector：
1 GOOGL 984526487552
2 GOOG 983797399552
3 FB 672216645632
4 VZ 235369431040
5 T 219592507392

['GOOGL', 'GOOG', 'FB', 'VZ', 'T']

In [13]:
Consumer_Discretionary_top5 = cap_sp500_tickers(Consumer_Discretionary,'Consumer Discretionary')
Consumer_Discretionary_top5

The Top 5 Companies from Consumer Discretionary sector：
1 AMZN 1300186005504
2 HD 266906206208
3 NKE 154165673984
4 MCD 141409468416
5 LOW 98663784448

['AMZN', 'HD', 'NKE', 'MCD', 'LOW']

In [16]:
Consumer_Staples_top5 = cap_sp500_tickers(Consumer_Staples,'Consumer Staples')
Consumer_Staples_top5

KeyError: 'regularMarketPrice'

In [17]:
Utilities_top5 = cap_sp500_tickers(Utilities,'Utilities')
Utilities_top5

The Top 5 Companies from Utilities sector：
1 NEE 122905788416
2 D 71680434176
3 DUK 64402513920
4 SO 59841249280
5 AEP 40826126336

['NEE', 'D', 'DUK', 'SO', 'AEP']

In [22]:
Financials_top5 = cap_sp500_tickers(Financials,'Financials')
Financials_top5

KeyError: 'regularMarketPrice'

In [18]:
Materials_top5 = cap_sp500_tickers(Materials,'Materials')
Materials_top5

The Top 5 Companies from Materials sector：
1 LIN 108981133312
2 ECL 58352861184
3 APD 52852809728
4 SHW 52143718400
5 NEM 44864503808

['LIN', 'ECL', 'APD', 'SHW', 'NEM']

In [19]:
Real_Estate_top5 = cap_sp500_tickers(Real_Estate,'RealEstate')
Real_Estate_top5

The Top 5 Companies from RealEstate sector：
1 AMT 117092630528
2 PLD 71418667008
3 CCI 70487179264
4 EQIX 61872074752
5 DLR 37868351488

['AMT', 'PLD', 'CCI', 'EQIX', 'DLR']

In [20]:
Energy_top5 = cap_sp500_tickers(Energy,'Energy')
Energy_top5

The Top 5 Companies from Energy sector：
1 XOM 203272568832
2 CVX 174954692608
3 COP 47739219968
4 KMI 36014227456
5 PSX 33558472704

['XOM', 'CVX', 'COP', 'KMI', 'PSX']

In [33]:
data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2017-04-30")
data

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2017-01-03,225.830002,223.880005,225.039993,225.240005,91366500.0,211.552551
2017-01-04,226.750000,225.610001,225.619995,226.580002,78744400.0,212.811111
2017-01-05,226.580002,225.479996,226.270004,226.399994,78379000.0,212.642044
2017-01-06,227.750000,225.899994,226.529999,227.210007,71559900.0,213.402817
2017-01-09,227.070007,226.419998,226.910004,226.460007,46939700.0,212.698441
...,...,...,...,...,...,...
2017-04-24,237.410004,234.559998,237.179993,237.169998,119209900.0,223.726654
2017-04-25,238.949997,237.809998,237.910004,238.550003,76698300.0,225.028427
2017-04-26,239.529999,238.350006,238.509995,238.399994,84702500.0,224.886948
2017-04-27,238.949997,237.979996,238.770004,238.600006,57410300.0,225.075592
2017-04-28,238.929993,237.929993,238.899994,238.080002,63532800.0,224.585098

In [36]:
cap = pdr.get_data_yahoo("SPY")

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2015-06-18,213.339996,210.630005,211.309998,212.779999,165867900.0,192.548340
2015-06-19,211.550003,210.360001,211.460007,210.809998,130478700.0,191.693558
2015-06-22,212.589996,211.639999,211.910004,211.889999,70696000.0,192.675644
2015-06-23,212.440002,211.570007,212.139999,212.039993,68476800.0,192.812057
2015-06-24,212.169998,210.470001,211.720001,210.500000,92307300.0,191.411682
...,...,...,...,...,...,...
2020-06-10,322.390015,318.220001,321.420013,319.000000,95000800.0,319.000000
2020-06-11,312.149994,300.010010,311.459991,300.609985,209243600.0,300.609985
2020-06-12,309.079987,298.600006,308.239990,304.209991,194529100.0,304.209991
2020-06-15,308.279999,296.739990,298.019989,307.049988,135147500.0,307.049988
2020-06-16,315.640015,307.670013,315.480011,313.599487,84863824.0,313.599487