In [2]:
import pandas as pd

# TWO WAYS TO GET DATA

# 1. using Cryptocompare API

In [35]:
# For the dataframe, meanings of each column:
# open, the price at which the period opened,
# high, the highest price reached during the period,
# low, the lowest price reached during the period,
# close, the price at which the period closed,
# volumefrom, the volume in the base currency that things are traded into,
# volumeto, the volume in the currency that is being traded.

btc

In [1]:
from_symbol='BTC'
to_symbol='USD'
exchange = 'Bitstamp'
datetime_interval = 'day'

In [3]:
import requests
from datetime import datetime
def get_filename(from_symbol, to_symbol, exchange, datetime_interval, download_date):
    return '%s_%s_%s_%s_%s.csv' % (from_symbol, to_symbol, exchange, datetime_interval, download_date)
def download_data(from_symbol, to_symbol, exchange, datetime_interval):
    supported_intervals = {'minute', 'hour', 'day'}
    assert datetime_interval in supported_intervals,\
        'datetime_interval should be one of %s' % supported_intervals
    print('Downloading %s trading data for %s %s from %s' %
          (datetime_interval, from_symbol, to_symbol, exchange))
    base_url = 'https://min-api.cryptocompare.com/data/histo'
    url = '%s%s' % (base_url, datetime_interval)
    params = {'fsym': from_symbol, 'tsym': to_symbol,
              'limit': 2000, 'aggregate': 1,
              'e': exchange}
    request = requests.get(url, params=params)
    data = request.json()
    return data
def convert_to_dataframe(data):
    df = pd.io.json.json_normalize(data, ['Data'])
    df['datetime'] = pd.to_datetime(df.time, unit='s')
    df = df[['datetime', 'low', 'high', 'open',
             'close', 'volumefrom', 'volumeto']]
    return df
def filter_empty_datapoints(df):
    indices = df[df.sum(axis=1) == 0].index
    print('Filtering %d empty datapoints' % indices.shape[0])
    df = df.drop(indices)
    return df
data = download_data(from_symbol, to_symbol, exchange, datetime_interval)
df = convert_to_dataframe(data)
df = filter_empty_datapoints(df)
current_datetime = datetime.now().date().isoformat()
filename = get_filename(from_symbol, to_symbol, exchange, datetime_interval, current_datetime)
print('Saving data to %s' % filename)
df.to_csv(filename, index=False)

Downloading day trading data for BTC USD from Bitstamp
Filtering 0 empty datapoints
Saving data to BTC_USD_Bitstamp_day_2020-07-21.csv

/Users/miaoyuesun/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:20: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

In [4]:
import pandas as pd
def read_dataset(filename):
    print('Reading data from %s' % filename)
    df = pd.read_csv(filename)
    # change type from object to datetime
    df.datetime = pd.to_datetime(df.datetime) 
    df = df.set_index('datetime') 
    df = df.sort_index() # sort by datetime
    print(df.shape)
    return df
df = read_dataset(filename)

Reading data from BTC_USD_Bitstamp_day_2020-07-21.csv
(2001, 6)

In [5]:
df

                low     high     open    close  volumefrom     volumeto
datetime
2015-01-29   220.00   242.18   236.20   234.75    26178.79   6076004.20
2015-01-30   227.26   244.98   234.75   232.60    19832.17   4653564.37
2015-01-31   215.75   234.80   232.60   217.98    19706.27   4494529.82
2015-02-01   208.48   220.81   217.98   214.80     6189.01   1336586.85
2015-02-02   214.80   241.98   214.80   237.97     6423.56   1494778.57
...             ...      ...      ...      ...         ...          ...
2020-07-17  9073.53  9184.28  9132.87  9156.50     3593.50  32814246.99
2020-07-18  9122.72  9214.63  9156.50  9177.43     1358.29  12449177.45
2020-07-19  9106.30  9243.36  9177.43  9211.99     1585.40  14518309.98
2020-07-20  9128.21  9224.73  9211.99  9162.43     3064.81  28118444.21
2020-07-21  9152.23  9442.89  9162.43  9423.99     3614.60  33703608.46

[2001 rows x 6 columns]

bch

In [6]:
from_symbol='BCH'
to_symbol='USD'
exchange = 'Bitstamp'
datetime_interval = 'day'
data = download_data(from_symbol, to_symbol, exchange,datetime_interval)
df = convert_to_dataframe(data)
df = filter_empty_datapoints(df)
current_datetime = datetime.now().date().isoformat()
filename = get_filename(from_symbol, to_symbol, exchange,datetime_interval, current_datetime)
print('Saving data to %s' % filename)
df.to_csv(filename, index=False)

Downloading day trading data for BCH USD from Bitstamp
Filtering 1064 empty datapoints
Saving data to BCH_USD_Bitstamp_day_2020-07-21.csv

/Users/miaoyuesun/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:20: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

In [7]:
df = read_dataset(filename)

Reading data from BCH_USD_Bitstamp_day_2020-07-21.csv
(937, 6)

In [8]:
df

                low     high     open    close  volumefrom     volumeto
datetime
2017-12-28  2345.00  2511.10  2406.54  2498.00     3304.50   8019003.99
2017-12-29  2298.57  2895.00  2498.00  2600.00    11900.50  30621949.45
2017-12-30  2120.00  2628.91  2600.00  2240.42     9515.13  22311057.67
2017-12-31  2189.00  2504.00  2240.42  2377.00     3199.33   7550115.42
2018-01-01  2250.00  2410.00  2377.00  2310.00     2772.40   6460996.05
...             ...      ...      ...      ...         ...          ...
2020-07-17   221.85   225.43   224.11   222.82     3384.53    756027.75
2020-07-18   222.33   226.50   222.82   224.75     2690.23    603805.02
2020-07-19   220.49   228.84   224.75   227.93     1717.54    385332.24
2020-07-20   220.82   227.93   227.93   222.83     1570.25    352337.31
2020-07-21   222.44   232.85   222.83   231.25     2051.40    468504.64

[937 rows x 6 columns]

ltc

In [9]:
from_symbol='LTC'
to_symbol='USD'
exchange = 'Bitstamp'
datetime_interval = 'day'
data = download_data(from_symbol, to_symbol, exchange,datetime_interval)
df = convert_to_dataframe(data)
df = filter_empty_datapoints(df)
current_datetime = datetime.now().date().isoformat()
filename = get_filename(from_symbol, to_symbol, exchange,datetime_interval, current_datetime)
print('Saving data to %s' % filename)
df.to_csv(filename, index=False)

Downloading day trading data for LTC USD from Bitstamp
Filtering 878 empty datapoints
Saving data to LTC_USD_Bitstamp_day_2020-07-21.csv

/Users/miaoyuesun/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:20: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

In [10]:
df = read_dataset(filename)

Reading data from LTC_USD_Bitstamp_day_2020-07-21.csv
(1123, 6)

In [11]:
df

              low   high   open  close  volumefrom    volumeto
datetime
2017-06-25  38.55  43.21  43.03  40.90     7875.20   321778.89
2017-06-26  34.89  41.89  40.90  38.34    51559.95  1951395.52
2017-06-27  34.44  40.34  38.34  40.33    32438.14  1192329.47
2017-06-28  37.96  42.99  40.33  42.04    28966.58  1199844.05
2017-06-29  39.64  42.04  42.04  40.50    14557.53   596600.26
...           ...    ...    ...    ...         ...         ...
2020-07-17  41.65  42.43  42.08  41.86    24092.04  1011379.21
2020-07-18  41.73  42.91  41.86  42.46    17778.07   752807.66
2020-07-19  41.90  42.89  42.46  42.67    11514.79   487040.67
2020-07-20  41.44  42.76  42.67  41.98    15947.36   671402.89
2020-07-21  41.98  44.13  41.98  43.77    18582.15   807349.10

[1123 rows x 6 columns]

eth

In [12]:
from_symbol='ETH'
to_symbol='USD'
exchange = 'Bitstamp'
datetime_interval = 'day'
data = download_data(from_symbol, to_symbol, exchange,datetime_interval)
df = convert_to_dataframe(data)
df = filter_empty_datapoints(df)
current_datetime = datetime.now().date().isoformat()
filename = get_filename(from_symbol, to_symbol, exchange,datetime_interval, current_datetime)
print('Saving data to %s' % filename)
df.to_csv(filename, index=False)

Downloading day trading data for ETH USD from Bitstamp
Filtering 1015 empty datapoints
Saving data to ETH_USD_Bitstamp_day_2020-07-21.csv

/Users/miaoyuesun/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:20: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

In [13]:
df = read_dataset(filename)

Reading data from ETH_USD_Bitstamp_day_2020-07-21.csv
(986, 6)

In [14]:
df

               low    high    open   close  volumefrom     volumeto
datetime
2017-11-09  317.29  331.70  322.15  321.32    13118.15   4270934.90
2017-11-10  291.00  325.61  321.32  298.66    34411.65  10580539.65
2017-11-11  298.00  322.19  298.66  315.76    23836.74   7328431.51
2017-11-12  300.11  318.98  315.76  306.10    48200.80  14854823.36
2017-11-13  305.91  320.69  306.10  316.14    36613.50  11517856.30
...            ...     ...     ...     ...         ...          ...
2020-07-17  231.32  234.61  233.56  232.59    21851.47   5089656.10
2020-07-18  232.26  237.14  232.59  235.84    10615.02   2490148.22
2020-07-19  233.28  239.98  235.84  239.24    15601.36   3679658.82
2020-07-20  234.09  239.82  239.24  235.98    23698.50   5626969.69
2020-07-21  235.58  245.24  235.98  244.24    29681.20   7185404.52

[986 rows x 6 columns]

# 2. using Coinmarketcap API

In [15]:
from requests import Request,Session
from requests.exceptions import ConnectionError,Timeout,TooManyRedirects
import json

# GET DATA OF CYRPOTOCURRENCY
url ='https://pro-api.coinmarketcap.com/v1/cryptocurrency/map'

parameters = {'symbol':'BSV,BCH,LTC,BTC,ETH,ETC,HT,OKB,BNB'}

headers = {'Accepts':'application/json','X-CMC_PRO_API_KEY':'18ef157c-1ab3-465b-8169-e0aef0f6bd60',}

session = Session()

session.headers.update(headers)

try:
    response = session.get(url,params=parameters)
    data = json.loads(response.text)
    print(data)

except(ConnectionError,Timeout,TooManyRedirects) as e:
    print(e)

{'status': {'timestamp': '2020-07-21T14:14:36.851Z', 'error_code': 0, 'error_message': None, 'elapsed': 16, 'credit_count': 1, 'notice': None}, 'data': [{'id': 1831, 'name': 'Bitcoin Cash', 'symbol': 'BCH', 'slug': 'bitcoin-cash', 'is_active': 1, 'rank': 5, 'first_historical_data': '2017-07-23T16:29:27.000Z', 'last_historical_data': '2020-07-21T14:09:03.000Z', 'platform': None}, {'id': 1839, 'name': 'Binance Coin', 'symbol': 'BNB', 'slug': 'binance-coin', 'is_active': 1, 'rank': 9, 'first_historical_data': '2017-07-25T04:30:05.000Z', 'last_historical_data': '2020-07-21T14:09:03.000Z', 'platform': None}, {'id': 3602, 'name': 'Bitcoin SV', 'symbol': 'BSV', 'slug': 'bitcoin-sv', 'is_active': 1, 'rank': 6, 'first_historical_data': '2018-11-09T02:34:34.000Z', 'last_historical_data': '2020-07-21T14:09:13.000Z', 'platform': None}, {'id': 1, 'name': 'Bitcoin', 'symbol': 'BTC', 'slug': 'bitcoin', 'is_active': 1, 'rank': 1, 'first_historical_data': '2013-04-28T18:47:21.000Z', 'last_historical_data': '2020-07-21T14:09:01.000Z', 'platform': None}, {'id': 1321, 'name': 'Ethereum Classic', 'symbol': 'ETC', 'slug': 'ethereum-classic', 'is_active': 1, 'rank': 24, 'first_historical_data': '2016-07-24T13:44:30.000Z', 'last_historical_data': '2020-07-21T14:14:06.000Z', 'platform': None}, {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'is_active': 1, 'rank': 2, 'first_historical_data': '2015-08-07T14:49:30.000Z', 'last_historical_data': '2020-07-21T14:14:05.000Z', 'platform': None}, {'id': 2502, 'name': 'Huobi Token', 'symbol': 'HT', 'slug': 'huobi-token', 'is_active': 1, 'rank': 20, 'first_historical_data': '2018-02-03T19:54:29.000Z', 'last_historical_data': '2020-07-21T14:09:10.000Z', 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0x6f259637dcd74c767781e37bc6133cd6a68aa161'}}, {'id': 2, 'name': 'Litecoin', 'symbol': 'LTC', 'slug': 'litecoin', 'is_active': 1, 'rank': 8, 'first_historical_data': '2013-04-28T18:47:22.000Z', 'last_historical_data': '2020-07-21T14:09:01.000Z', 'platform': None}, {'id': 3897, 'name': 'OKB', 'symbol': 'OKB', 'slug': 'okb', 'is_active': 1, 'rank': 36, 'first_historical_data': '2019-04-30T21:19:09.000Z', 'last_historical_data': '2020-07-21T14:09:13.000Z', 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0x75231f58b43240c9718dd58b4967c5114342a86c'}}]}

In [16]:
data

{'status': {'timestamp': '2020-07-21T14:14:36.851Z',
  'error_code': 0,
  'error_message': None,
  'elapsed': 16,
  'credit_count': 1,
  'notice': None},
 'data': [{'id': 1831,
   'name': 'Bitcoin Cash',
   'symbol': 'BCH',
   'slug': 'bitcoin-cash',
   'is_active': 1,
   'rank': 5,
   'first_historical_data': '2017-07-23T16:29:27.000Z',
   'last_historical_data': '2020-07-21T14:09:03.000Z',
   'platform': None},
  {'id': 1839,
   'name': 'Binance Coin',
   'symbol': 'BNB',
   'slug': 'binance-coin',
   'is_active': 1,
   'rank': 9,
   'first_historical_data': '2017-07-25T04:30:05.000Z',
   'last_historical_data': '2020-07-21T14:09:03.000Z',
   'platform': None},
  {'id': 3602,
   'name': 'Bitcoin SV',
   'symbol': 'BSV',
   'slug': 'bitcoin-sv',
   'is_active': 1,
   'rank': 6,
   'first_historical_data': '2018-11-09T02:34:34.000Z',
   'last_historical_data': '2020-07-21T14:09:13.000Z',
   'platform': None},
  {'id': 1,
   'name': 'Bitcoin',
   'symbol': 'BTC',
   'slug': 'bitcoin',
   'is_active': 1,
   'rank': 1,
   'first_historical_data': '2013-04-28T18:47:21.000Z',
   'last_historical_data': '2020-07-21T14:09:01.000Z',
   'platform': None},
  {'id': 1321,
   'name': 'Ethereum Classic',
   'symbol': 'ETC',
   'slug': 'ethereum-classic',
   'is_active': 1,
   'rank': 24,
   'first_historical_data': '2016-07-24T13:44:30.000Z',
   'last_historical_data': '2020-07-21T14:14:06.000Z',
   'platform': None},
  {'id': 1027,
   'name': 'Ethereum',
   'symbol': 'ETH',
   'slug': 'ethereum',
   'is_active': 1,
   'rank': 2,
   'first_historical_data': '2015-08-07T14:49:30.000Z',
   'last_historical_data': '2020-07-21T14:14:05.000Z',
   'platform': None},
  {'id': 2502,
   'name': 'Huobi Token',
   'symbol': 'HT',
   'slug': 'huobi-token',
   'is_active': 1,
   'rank': 20,
   'first_historical_data': '2018-02-03T19:54:29.000Z',
   'last_historical_data': '2020-07-21T14:09:10.000Z',
   'platform': {'id': 1027,
    'name': 'Ethereum',
    'symbol': 'ETH',
    'slug': 'ethereum',
    'token_address': '0x6f259637dcd74c767781e37bc6133cd6a68aa161'}},
  {'id': 2,
   'name': 'Litecoin',
   'symbol': 'LTC',
   'slug': 'litecoin',
   'is_active': 1,
   'rank': 8,
   'first_historical_data': '2013-04-28T18:47:22.000Z',
   'last_historical_data': '2020-07-21T14:09:01.000Z',
   'platform': None},
  {'id': 3897,
   'name': 'OKB',
   'symbol': 'OKB',
   'slug': 'okb',
   'is_active': 1,
   'rank': 36,
   'first_historical_data': '2019-04-30T21:19:09.000Z',
   'last_historical_data': '2020-07-21T14:09:13.000Z',
   'platform': {'id': 1027,
    'name': 'Ethereum',
    'symbol': 'ETH',
    'slug': 'ethereum',
    'token_address': '0x75231f58b43240c9718dd58b4967c5114342a86c'}}]}