In [27]:
import pandas as pd, numpy as np
np.set_printoptions(suppress=True)# 关掉科学计数法
import glob
import os
import csv
# 一次性merge多个pct_chg
from functools import reduce
from datetime import datetime, timedelta
import statsmodels.api as sm
from statsmodels import regression

# import yfinance as yf
import tushare as ts
import time, urllib
ts.set_token('8ef5ec61cdd848715c57c11d58dd71da1271f76b2420d2bac8aef123')
pro = ts.pro_api('8ef5ec61cdd848715c57c11d58dd71da1271f76b2420d2bac8aef123')

import matplotlib
import matplotlib.pyplot as plt
# plt.rcParams['font.sans-serif']=['KaiTi']
# plt.rcParams['axes.unicode_minus'] = False

import seaborn as sns
%matplotlib inline
sns.set(context='notebook', style='darkgrid', palette='deep', font='sans-serif', font_scale=1, color_codes=False, rc=None)


from plotly.graph_objs import Scatter,Layout
import plotly
import plotly.offline as py
import numpy as np
import plotly.graph_objs as go

#setting offilne
plotly.offline.init_notebook_mode(connected=True)

from research_toolbox_all_in_one import *
# from research_toolbox_all_in_one import calc_macd_signals

In [10]:
ch_db_path = "/Users/miaoyuesun/Code_Workspace/brad_public_workspace_mac/data/CH_database/"

In [12]:
leaders_tickers_df = pd.read_csv("20200309_110_A_shares_industry_leaders.csv")

In [13]:
leaders_tickers = list(leaders_tickers_df['tickers'])

In [14]:
industry_leaders_mkt_df = get_mkt_data_df(ch_db_path, leaders_tickers, 'trade_date')

In [15]:
tgt_stocks_macd_signals = calc_macd_signals(industry_leaders_mkt_df, leaders_tickers, 'ts_code', 'string','close')
tgt_most_recent_stocks_macd_signals = get_last_signals_macd(tgt_stocks_macd_signals, 'trade_date','ts_code')
# This could be different from our current position holdings
tgt_most_recent_stocks_macd_signals['TYPE'] = 'TARGET'
tgt_most_recent_stocks_macd_signals.sort_values("ts_code", inplace=True)
# If there are empty positions then don't use this function:
# signal_df = merge_current_pos_with_target_pos(ch_db_path, cur_positions, tgt_most_recent_stocks_macd_signals, \
#                                               'ts_code','trade_date','string','close')

/Users/miaoyuesun/anaconda3/lib/python3.5/site-packages/pandas/compat/_optional.py:106: UserWarning:

Pandas requires version '2.6.2' or newer of 'numexpr' (version '2.6.1' currently installed).

/Users/miaoyuesun/Code_Workspace/brad_public_workspace_mac/quant_research/research_toolbox_all_in_one.py:229: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/miaoyuesun/Code_Workspace/brad_public_workspace_mac/quant_research/research_toolbox_all_in_one.py:230: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/miaoyuesun/Code_Workspace/brad_public_workspace_mac/quant_research/research_toolbox_all_in_one.py:231: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/miaoyuesun/Code_Workspace/brad_public_workspace_mac/quant_research/research_toolbox_all_in_one.py:232: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
df_actions = tgt_most_recent_stocks_macd_signals[(tgt_most_recent_stocks_macd_signals['SIGNAL_ACTION']=="LONG")|\
                                                (tgt_most_recent_stocks_macd_signals['SIGNAL_ACTION']=="SHORT")]

In [17]:
df_actions

        trade_date    ts_code SIGNAL_STATUS SIGNAL_ACTION    TYPE
2386    2020-03-09  000063.SZ          空头状态         SHORT  TARGET
30764   2020-03-09  000723.SZ          空头状态         SHORT  TARGET
41928   2020-03-09  002027.SZ          空头状态         SHORT  TARGET
69788   2020-03-09  002195.SZ          空头状态         SHORT  TARGET
44090   2020-03-09  002481.SZ          空头状态         SHORT  TARGET
99043   2020-03-09  003816.SZ          空头状态         SHORT  TARGET
64642   2020-03-09  300058.SZ          空头状态         SHORT  TARGET
169259  2020-03-09  600175.SH          空头状态         SHORT  TARGET
146023  2020-03-09  600221.SH          空头状态         SHORT  TARGET
181424  2020-03-09  600568.SH          空头状态         SHORT  TARGET
172207  2020-03-09  601212.SH          空头状态         SHORT  TARGET
64959   2020-03-09  601319.SH          空头状态         SHORT  TARGET
176816  2020-03-09  601777.SH          空头状态         SHORT  TARGET

In [24]:
tgt_returns = get_date_price_code_return_list(ch_db_path, leaders_tickers, 'trade_date', 'close', 'ts_code')
tgt_merged_returns = merge_dfs_by_ticker(tgt_returns, "trade_date")

In [25]:
df_wts, stocks, weights = get_df_wts(tgt_merged_returns)

In [30]:
# draw_risk_parity_pie(weights, stocks)
df_wts.columns = ['ts_code','weights']
# df_wts.sort_values("weights", ascending=False)

      ts_code   weights
16  601288.SH  0.028084
33  600028.SH  0.016739
22  002252.SZ  0.016616
7   600887.SH  0.012938
83  600795.SH  0.012877
..        ...       ...
63  000758.SZ  0.006698
1   300059.SZ  0.006595
53  300370.SZ  0.006007
71  300409.SZ  0.005814
4   601816.SH  0.003931

[110 rows x 2 columns]

In [35]:
df_actions_with_weights = df_wts.merge(df_actions, on ='ts_code')
df_actions_with_weights['weights_enlarged'] = df_actions_with_weights['weights']*2
tickers_to_trade = list(df_actions_with_weights['ts_code'])
tickers_to_trade_closes = get_date_price_code_df(ch_db_path, tickers_to_trade, 'trade_date', 'close', 'ts_code')
last_date = '2020-03-09'
tickers_to_trade_closes_last_date = tickers_to_trade_closes[tickers_to_trade_closes['trade_date'] == last_date]

In [36]:
tickers_to_trade_closes_last_date

       trade_date  close    ts_code
2386   2020-03-09  51.01  000063.SZ
4550   2020-03-09   7.91  000723.SZ
6918   2020-03-09   5.26  002027.SZ
9080   2020-03-09  11.94  002481.SZ
11311  2020-03-09   6.81  300058.SZ
11628  2020-03-09   6.89  601319.SH
14005  2020-03-09   3.10  002195.SZ
14133  2020-03-09   3.15  003816.SZ
16450  2020-03-09   1.75  600221.SH
18735  2020-03-09   1.45  600175.SH
19439  2020-03-09   3.14  601212.SH
21655  2020-03-09   2.79  601777.SH
23806  2020-03-09   1.71  600568.SH

In [37]:
df_actions_with_weights = df_actions_with_weights.merge(tickers_to_trade_closes_last_date, on = ['trade_date','ts_code'])
account_values = 70000
df_actions_with_weights['tgt_shares'] = account_values*\
                                        df_actions_with_weights['weights_enlarged']/\
                                        df_actions_with_weights['close']

In [38]:
df_actions_with_weights

,ts_code,weights,trade_date,SIGNAL_STATUS,SIGNAL_ACTION,TYPE,weights_enlarged,close,tgt_shares
0,000063.SZ,0.008178,2020-03-09,空头状态,SHORT,TARGET,0.016355,51.01,22.444093
1,000723.SZ,0.008253,2020-03-09,空头状态,SHORT,TARGET,0.016506,7.91,146.074456
2,002027.SZ,0.009710,2020-03-09,空头状态,SHORT,TARGET,0.019419,5.26,258.431959
3,002481.SZ,0.010780,2020-03-09,空头状态,SHORT,TARGET,0.021560,11.94,126.396463
4,300058.SZ,0.008649,2020-03-09,空头状态,SHORT,TARGET,0.017297,6.81,177.799625
5,601319.SH,0.008045,2020-03-09,空头状态,SHORT,TARGET,0.016089,6.89,163.458825
6,002195.SZ,0.006771,2020-03-09,空头状态,SHORT,TARGET,0.013541,3.10,305.773023
7,003816.SZ,0.011138,2020-03-09,空头状态,SHORT,TARGET,0.022277,3.15,495.037104
8,600221.SH,0.009956,2020-03-09,空头状态,SHORT,TARGET,0.019912,1.75,796.468981
9,600175.SH,0.008203,2020-03-09,空头状态,SHORT,TARGET,0.016406,1.45,792.004222
10,601212.SH,0.011405,2020-03-09,空头状态,SHORT,TARGET,0.022810,3.14,508.492518
11,601777.SH,0.007139,2020-03-09,空头状态,SHORT,TARGET,0.014279,2.79,358.246702
12,600568.SH,0.010269,2020-03-09,空头状态,SHORT,TARGET,0.020538,1.71,840.755176